# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Network_Gui.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(941, 780)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 130, 921, 521))
        self.widget.setObjectName("widget")
        self.picture1 = QtWidgets.QLabel(self.centralwidget)
        self.picture1.setGeometry(QtCore.QRect(690, 10, 231, 101))
        self.picture1.setObjectName("picture1")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(480, 10, 181, 30))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.eraseButton = QtWidgets.QPushButton(self.centralwidget)
        self.eraseButton.setGeometry(QtCore.QRect(830, 670, 85, 28))
        self.eraseButton.setObjectName("eraseButton")
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(290, 11, 178, 111))
        self.widget1.setObjectName("widget1")
        self.formLayout = QtWidgets.QFormLayout(self.widget1)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.node_label = QtWidgets.QLabel(self.widget1)
        self.node_label.setObjectName("node_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.node_label)
        self.edge_label = QtWidgets.QLabel(self.widget1)
        self.edge_label.setObjectName("edge_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.edge_label)
        self.total_length_label = QtWidgets.QLabel(self.widget1)
        self.total_length_label.setObjectName("total_length_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.total_length_label)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(30, 20, 112, 101))
        self.widget2.setObjectName("widget2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget2)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.Export_Nodes = QtWidgets.QPushButton(self.widget2)
        self.Export_Nodes.setObjectName("Export_Nodes")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.Export_Nodes)
        self.Export_Edges = QtWidgets.QPushButton(self.widget2)
        self.Export_Edges.setObjectName("Export_Edges")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.Export_Edges)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 941, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExport_Node_Data = QtWidgets.QAction(MainWindow)
        self.actionExport_Node_Data.setObjectName("actionExport_Node_Data")
        self.actionExport_Edge_Data = QtWidgets.QAction(MainWindow)
        self.actionExport_Edge_Data.setObjectName("actionExport_Edge_Data")
        self.actionExport_All = QtWidgets.QAction(MainWindow)
        self.actionExport_All.setObjectName("actionExport_All")
        self.actionExport_Edge_Data_2 = QtWidgets.QAction(MainWindow)
        self.actionExport_Edge_Data_2.setObjectName("actionExport_Edge_Data_2")
        self.actionExport_All_2 = QtWidgets.QAction(MainWindow)
        self.actionExport_All_2.setObjectName("actionExport_All_2")
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.picture1.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/logo.png\"/></p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Node - Edge - Mode"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Node - Mode"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Edge - Mode"))
        self.eraseButton.setText(_translate("MainWindow", "Reset"))
        self.node_label.setText(_translate("MainWindow", "<html><head/><body><p>Nodes: </p><p>0</p></body></html>"))
        self.edge_label.setText(_translate("MainWindow", "<html><head/><body><p>Edges: </p><p>0</p></body></html>"))
        self.total_length_label.setText(_translate("MainWindow", "<html><head/><body><p>Total Edge Length:</p><p>0</p></body></html>"))
        self.Export_Nodes.setText(_translate("MainWindow", "Export Nodes"))
        self.Export_Edges.setText(_translate("MainWindow", "Export Edges"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExport_Node_Data.setText(_translate("MainWindow", "Export Node Data"))
        self.actionExport_Edge_Data.setText(_translate("MainWindow", "Export Edge Data"))
        self.actionExport_All.setText(_translate("MainWindow", "Export All"))
        self.actionExport_Edge_Data_2.setText(_translate("MainWindow", "Export Edge Data"))
        self.actionExport_All_2.setText(_translate("MainWindow", "Export All"))

import pictures_rc
